language: node_js
node_js:
  - "6"

## test
script:
  - make test

## deploy
sudo: required
services:
  - docker
deploy:
  - provider: script
    skip_cleanup: true # use exactly same stuff for deploy as for test
    script: make release-prod
    on:
      branch: master
  - provider: script
    skip_cleanup: true # use exactly same stuff for deploy as for test
    script: make release-staging
    on:
      branch: maio/next
